### ISSUE TITLE
Error returned from server: UNSUPPORTED_LANG

### ISSUE THREAD

**Issue by digika-ding** [TuringSoftware/CrystalFetch#13] opened 2023-08-07 04:09 UTC
```

                  ,MMMM.           Host        -  weibingding@Weibings-MacBook-Pro.local
                .MMMMMM            Machine     -  MacBookPro18,1
                MMMMM,             Kernel      -  22.5.0
      .;MMMMM:' MMMMMMMMMM;.       OS          -  macOS 13.4.1 Ventura
    MMMMMMMMMMMMNWMMMMMMMMMMM:     DE          -  Aqua
  .MMMMMMMMMMMMMMMMMMMMMMMMWM.     WM          -  Quartz Compositor
  MMMMMMMMMMMMMMMMMMMMMMMMM.       Packages    -  23 (Homebrew)
 ;MMMMMMMMMMMMMMMMMMMMMMMM:        Terminal    -  alacritty
 :MMMMMMMMMMMMMMMMMMMMMMMM:        Shell       -  zsh
 .MMMMMMMMMMMMMMMMMMMMMMMMM.       Uptime      -  14d 17h 30m
  MMMMMMMMMMMMMMMMMMMMMMMMMMM.     CPU         -  Apple M1 Pro (10)
   .MMMMMMMMMMMMMMMMMMMMMMMMMM.    Resolution  -  3456x2234@120fps (as 1728x1117)
     MMMMMMMMMMMMMMMMMMMMMMMM                     2880x5120@60fps (as 1440x2560)
      ;MMMMMMMMMMMMMMMMMMMM.                      2360x1640@60fps (as 1180x820)
        .MMMM,.    .MMMM,.         Brightness  -  46%
                                   CPU Load    -  36%
                                   Memory      -  14.5 GB/33.6 GB
                                   Battery     -  96% & Discharging

```

CrystalFetch
Version 1.0.0 (1)

![image](https://github.com/TuringSoftware/CrystalFetch/assets/110518995/8a2c9d20-60c4-44d1-9e03-0fd2edaa23a6)

**Comment by digika-ding** [comment] 2023-08-08 03:49
> duplicate with #6.
> 
> You need to upgrade to version 1.0.1

I didn't receive any notifications from the Apple Store to update Crystal Fetch.

**Comment by theggs** [comment] 2023-08-08 04:28
according to the duplicate issue, app store version hasn't been updated. I think you can download from github release. https://github.com/TuringSoftware/CrystalFetch/releases

**Comment by digika-ding** [comment] 2023-08-08 04:45
Thank you for your response. Can you please explain why the App Store version hasn't been updated? Is there a specific reason to download from the GitHub release?

**Comment by theggs** [comment] 2023-08-08 04:47
I don't know why either. Maybe the repo owner knows more.

**Comment by osy** [comment] 2023-08-11 06:09
Duplicate of #2

**Closed by osy** 2023-08-11 06:09 UTC
