### ISSUE TITLE
Error returned from server: UNSUPPORTED_LANG

### ISSUE THREAD

**Issue by benyamynbrkyc** [TuringSoftware/CrystalFetch#6] opened 2023-08-02 19:51 UTC
I just installed CrystalFetch from the App Store and I get the following error alert when accessing any version of Windows from the left sidebar.

`Error returned from server: UNSUPPORTED_LANG`

![Screenshot 2023-08-02 at 21 50 08](https://github.com/TuringSoftware/CrystalFetch/assets/44731788/8f73eb07-720a-4863-8fc2-01db2bf36458)

**Comment by QuiRohn02** [comment] 2023-08-02 20:48
Have you selected the language?

**Comment by benyamynbrkyc** [comment] 2023-08-02 20:55
It looks like the App Store version has not been updated. I downloaded the .dmg from GitHub and everything works as expected. In the old version I was unable to specify both the language and edition. Thank you :)

**Comment by tonilampela** [comment] 2023-08-03 06:19
Same issue here with AppStore version... I assume there is version update coming to AppStore as I'd prefer to use it rather than direct download from Github?

**Comment by QuiRohn02** [comment] 2023-08-03 06:26
> Same issue here with AppStore version... I assume there is version update coming to AppStore as I'd prefer to use it rather than direct download from Github?

I don't know when the update will be released on the app store, so I suggest you download it from github

**Comment by osy** [comment] 2023-08-11 06:09
Duplicate of #2

**Closed by osy** 2023-08-11 06:09 UTC
